package com.bhoruka.bloodbank.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "BloodComponent")
public class BloodComponent {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey
    private String sampleId;

    @DynamoDBAttribute
    private String bloodGroup;

    @DynamoDBAttribute
    private Integer wbc;

    @DynamoDBAttribute
    private Integer pc;

    @DynamoDBAttribute
    private Integer ffp;

    @DynamoDBAttribute
    private Integer paedFfp;

    @DynamoDBAttribute
    private Integer plateletCone;

    @DynamoDBAttribute
    private Integer cryoPpt;

    @DynamoDBAttribute
    private Integer cfp;

    @DynamoDBAttribute
    private Date date;
}
