package com.bhoruka.bloodbank.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "Camp")
public class Camp {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey
    private String partnerId;

    @DynamoDBAttribute
    private Date dateOfCamp;

    @DynamoDBAttribute
    private Long expectedNoOfDonor;

    @DynamoDBAttribute
    private Long actualNoOfDonor;
}
