package com.bhoruka.bloodbank.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "Sample")
public class Sample {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey
    private String donorId;

    @DynamoDBAttribute
    private String segmentNumber;

    @DynamoDBAttribute
    private Date date;

    @DynamoDBAttribute
    private String typeOfBag;

    @DynamoDBAttribute
    private String bloodGroup;

    @DynamoDBAttribute
    private String arm;

    @DynamoDBAttribute
    private String remarks;

}
